### ISSUE TITLE
AssemblyInformationalVersion

### ISSUE THREAD

**Issue by ssvaidya** [mikefourie/MSBuildExtensionPack#18]
I am trying to use the AssemblyInfoTask and I have noticed that the task works just fine for the AssemblyVersion and AssemblyFileVersion attribute but fails to update the AssemblyInfo.cs file when I attempt to execute the AssemblyInformationalVersion attribute.

The original AssemblyInformationalVersion attribute in the file always remains intact and is never updated.

**Comment by mikefourie** [comment]
http://www.msbuildextensionpack.com/help/4.0.9.0/html/6a18646f-f1bc-5050-c4b8-c248c9e4fd91.htm
