### ISSUE TITLE
xpath question regarding using MSBuild.ExtensionPack.Xml.XmlFile :  AddElement

### ISSUE THREAD

**Issue by craighill179** [mikefourie/MSBuildExtensionPack#19]
I am trying to export the TFS global list , update it and import via witadmin
Basically we want to add build numbers that our uses a non-tfs format

I can check for existence and read them OK
MY issue is writing bvalues to the XM L file, I am not sure of the xpath value that is necessary to accomplish this

Suggestions??

SAMPLE  GlobalList.xml

<?xml version="1.0" encoding="utf-8"?>
<gl:GLOBALLISTS xmlns:gl="http://schemas.microsoft.com/VisualStudio/2005/workitemtracking/globallists">
  <GLOBALLIST name="Builds - Trillium">
    <LISTITEM value="TSQ_Build_AIX/TSQ_Build_AIX_20150107.1" />
    <LISTITEM value="MRB_Build/MRB_Build_20150107.3" />
    <LISTITEM value="TSQ_BuildAll/TSQ_BuildAll_20150107.3" />
    <LISTITEM value="ECS_Build_Unix/ECS_Build_Unix_20150107.1" />
    <LISTITEM value="SPF_Build_HPi64/SPF_Build_HPi64_20150107.3" />
    <LISTITEM value="SPF_Build_Linux/SPF_Build_Linux_20150107.3" />
    <LISTITEM value="SPF_Build_Aix6.1/SPF_Build_Aix6.1_20150107.3" />
    <LISTITEM value="SPF_Build_SunOS/SPF_Build_SunOS_20150107.2" />
    <LISTITEM value="TSQ_Deliver/TSQ_Deliver_20150107.1" />
    <LISTITEM value="SPF_Build_Aix6.1/SPF_Build_Aix6.1_20150107.4" />
    <LISTITEM value="SPF_Build_Windows/SPF_Build_Windows_20150107.3" />
    <LISTITEM value="SPF_Build_Linux/SPF_Build_Linux_20150107.4" />
    <LISTITEM value="SPF_Build_SunOS/SPF_Build_SunOS_20150107.3" />
    <LISTITEM value="SPF_Build_Windows/SPF_Build_Windows_20150107.4" />
  </GLOBALLIST>
  <GLOBALLIST name="Builds - SandboxDev">
    <LISTITEM value="TSSAutomationTest/TSSAutomationTest_20140701.6" />
    <LISTITEM value="TSSAutomationTest/TSSAutomationTest_20140701.7" />
    <LISTITEM value="TSSAutomationTest/TSSAutomationTest_20140701.8" />
    <LISTITEM value="TSSAutomationTest/TSSAutomationTest_20140701.9" />
    <LISTITEM value="TSSAutomationTest/TSSAutomationTest_20140701.10" />
    <LISTITEM value="TSSAutomationTest/TSSAutomationTest_20140701.11" />
    <LISTITEM value="TSSAutomationTest/TSSAutomationTest_20140701.12" />
    <LISTITEM value="TSSAutomationTest/TSSAutomationTest_20140701.13" />
    <LISTITEM value="TSSAutomationTest/TSSAutomationTest_20140701.14" />
    <LISTITEM value="TSSAutomationTest/TSSAutomationTest_20140701.15" />
  </GLOBALLIST>
  <GLOBALLIST name="BuildNumbers">
    <LISTITEM value="15.0.0.14365" />
    <LISTITEM value="15.0.0.15008" />
  </GLOBALLIST>
/gl:GLOBALLISTS

MSBUILD Script

<Target Name="UpdateGLBuildNumbers">

  <PropertyGroup>
    <WITADMIN>C:\Program Files (x86)\Microsoft Visual Studio 12.0\Common7\IDE\witadmin.exe</WITADMIN>
    <GLFile>$(MSBuildProjectDirectory)\GlobalList.xml</GLFile>
    <GLFile>C:\Temp\GlobalList.xml</GLFile>
    <BldNum>$(RELEASE_VERSION_DOT).$(BUILDNUMBER)</BldNum>
  </PropertyGroup>

  
  <ItemGroup>
    <getGLBuildNumbers Include="&quot;$(WITADMIN)&quot;"/>
    <getGLBuildNumbers Include="exportgloballist"/>
    <getGLBuildNumbers Include="/collection:$(collection)" />
    <getGLBuildNumbers Include="/f:$(GLFile)"/>
  </ItemGroup>

  
  <Exec Command="@(getGLBuildNumbers, ' ')" IgnoreExitCode="false" />

  <MSBuild.ExtensionPack.Xml.XmlFile
    File="$(GLFile)"
    XPath='//LISTITEM[@value="$(BldNum)"]'
    TaskAction="ReadElements">
    <Output ItemName="GLBuildNumbers" TaskParameter="Elements"/>
  </MSBuild.ExtensionPack.Xml.XmlFile>

  <Message Text = "$(BldNum) Exists In GL"   Condition="'%(GLBuildNumbers.value)'=='$(BldNum)'"/>
  <Message Text = "$(BldNum) Does Not Exist In GL"   Condition="'%(GLBuildNumbers.value)'!='$(BldNum)'"/>
  <Message Text = " "/>

  <MSBuild.ExtensionPack.Xml.XmlFile
       File="$(GLFile)"
       XPath='/GLOBALLIST[@name="BuildNumbers"]/LISTITEM'
       TaskAction="AddElement"
       Key="value"
       Value="$(BldNum)">
  </MSBuild.ExtensionPack.Xml.XmlFile>

</Target>

**Comment by craighill179** [comment]
for some reason the cut/pate ff for the global list and msbulild script did not post correctly

Global List:

<?xml version="1.0" encoding="utf-8"?>
<gl:GLOBALLISTS xmlns:gl="http://schemas.microsoft.com/VisualStudio/2005/workitemtracking/globallists">
  <GLOBALLIST name="Builds - Trillium">
    <LISTITEM value="TSQ_Build_AIX/TSQ_Build_AIX_20150107.1" />
    <LISTITEM value="MRB_Build/MRB_Build_20150107.3" />
    <LISTITEM value="TSQ_BuildAll/TSQ_BuildAll_20150107.3" />
    <LISTITEM value="ECS_Build_Unix/ECS_Build_Unix_20150107.1" />
    <LISTITEM value="SPF_Build_HPi64/SPF_Build_HPi64_20150107.3" />
    <LISTITEM value="SPF_Build_Linux/SPF_Build_Linux_20150107.3" />
    <LISTITEM value="SPF_Build_Aix6.1/SPF_Build_Aix6.1_20150107.3" />
    <LISTITEM value="SPF_Build_SunOS/SPF_Build_SunOS_20150107.2" />
    <LISTITEM value="TSQ_Deliver/TSQ_Deliver_20150107.1" />
    <LISTITEM value="SPF_Build_Aix6.1/SPF_Build_Aix6.1_20150107.4" />
    <LISTITEM value="SPF_Build_Windows/SPF_Build_Windows_20150107.3" />
    <LISTITEM value="SPF_Build_Linux/SPF_Build_Linux_20150107.4" />
    <LISTITEM value="SPF_Build_SunOS/SPF_Build_SunOS_20150107.3" />
    <LISTITEM value="SPF_Build_Windows/SPF_Build_Windows_20150107.4" />
  </GLOBALLIST>
  <GLOBALLIST name="Builds - SandboxDev">
    <LISTITEM value="TSSAutomationTest/TSSAutomationTest_20140701.6" />
    <LISTITEM value="TSSAutomationTest/TSSAutomationTest_20140701.7" />
    <LISTITEM value="TSSAutomationTest/TSSAutomationTest_20140701.8" />
    <LISTITEM value="TSSAutomationTest/TSSAutomationTest_20140701.9" />
    <LISTITEM value="TSSAutomationTest/TSSAutomationTest_20140701.10" />
    <LISTITEM value="TSSAutomationTest/TSSAutomationTest_20140701.11" />
    <LISTITEM value="TSSAutomationTest/TSSAutomationTest_20140701.12" />
    <LISTITEM value="TSSAutomationTest/TSSAutomationTest_20140701.13" />
    <LISTITEM value="TSSAutomationTest/TSSAutomationTest_20140701.14" />
    <LISTITEM value="TSSAutomationTest/TSSAutomationTest_20140701.15" />
  </GLOBALLIST>
  <GLOBALLIST name="BuildNumbers">
    <LISTITEM value="15.0.0.14365" />
    <LISTITEM value="15.0.0.15008" />
  </GLOBALLIST>
</gl:GLOBALLISTS>


MSBUILD Script:

<Target Name="UpdateGLBuildNumbers">

  <PropertyGroup>
    <WITADMIN>C:\Program Files (x86)\Microsoft Visual Studio 12.0\Common7\IDE\witadmin.exe</WITADMIN>
    <GLFile>$(MSBuildProjectDirectory)\GlobalList.xml</GLFile>
    <GLFile>C:\Temp\GlobalList.xml</GLFile>
    <BldNum>$(RELEASE_VERSION_DOT).$(BUILDNUMBER)</BldNum>
  </PropertyGroup>

  
  <ItemGroup>
    <getGLBuildNumbers Include="&quot;$(WITADMIN)&quot;"/>
    <getGLBuildNumbers Include="exportgloballist"/>
    <getGLBuildNumbers Include="/collection:$(collection)" />
    <getGLBuildNumbers Include="/f:$(GLFile)"/>
  </ItemGroup>

  
  <Exec Command="@(getGLBuildNumbers, ' ')" IgnoreExitCode="false" />

  <MSBuild.ExtensionPack.Xml.XmlFile
    File="$(GLFile)"
    XPath='//LISTITEM[@value="$(BldNum)"]'
    TaskAction="ReadElements">
    <Output ItemName="GLBuildNumbers" TaskParameter="Elements"/>
  </MSBuild.ExtensionPack.Xml.XmlFile>

  <Message Text = "$(BldNum) Exists In GL"   Condition="'%(GLBuildNumbers.value)'=='$(BldNum)'"/>
  <Message Text = "$(BldNum) Does Not Exist In GL"   Condition="'%(GLBuildNumbers.value)'!='$(BldNum)'"/>
  <Message Text = " "/>

  <MSBuild.ExtensionPack.Xml.XmlFile
       File="$(GLFile)"
       XPath='/GLOBALLIST[@name="BuildNumbers"]/LISTITEM'
       TaskAction="AddElement"
       Key="value"
       Value="$(BldNum)">
  </MSBuild.ExtensionPack.Xml.XmlFile>

</Target>

**Comment by craighill179** [comment]
<GLOBALLIST name="BuildNumbers">
    <LISTITEM value="15.0.0.14365" />
    <LISTITEM value="15.0.0.15008" />
  </GLOBALLIST>

**Comment by mikefourie** [comment]
is this still a problem?
