### ISSUE TITLE
Ionic.Zip.dll is missing in Binaries folder in Release 4.0.10.0 zip

### ISSUE THREAD

**Issue by icnocop** [mikefourie/MSBuildExtensionPack#20]
Hi.

Thank you for MSBuild Extension Pack 4.0.10.0.

Ionic.Zip.dll v1.9.1.8 is missing in the Binaries folder in the 4.0.10.0 Release zip file.

As a result, I get the following MSBuild error:
`error MSB4062: The "MSBuild.ExtensionPack.Framework.Guid" task could not be loaded from the assembly C:\Build\1\Third Party\MsBuild Extension Pack\4.0.10.0\Binaries\MSBuild.ExtensionPack.dll. Could not load file or assembly 'Ionic.Zip, Version=1.9.1.8, Culture=neutral, PublicKeyToken=edbe51ad942a3f5c' or one of its dependencies. The system cannot find the file specified. Confirm that the <UsingTask> declaration is correct, that the assembly and all its dependencies are available, and that the task contains a public class that implements Microsoft.Build.Framework.ITask.`

It exists in the v3.5.14.0 zip file though.

Thank you.

**Comment by mikefourie** [comment]
Thanks for letting me know. will fix in a few days when i push out a new release.
