### ISSUE TITLE
Error 2203 while installing

### ISSUE THREAD

**Issue by jjohnsonmt** [mikefourie/MSBuildExtensionPack#24]
Trying to install MSBuild Extension Pack 4.0.10.0 on my Windows server 2012 machine and am getting error 2203 while installing. 

I am using the x86 version.

**Comment by mikefourie** [comment]
sounds like some permission issue. try installing as admin.

**Comment by jjohnsonmt** [comment]
yeah. Temp directory did not have write permission. Thanks.
