### ISSUE TITLE
Parallel task doesn't support log paths with spaces

### ISSUE THREAD

**Issue by CrazeeeCoder** [mikefourie/MSBuildExtensionPack#26]
I am using the Parallel task and wanted to use the LogFilePath metadata value to change the log's output path.  I noticed that if there are spaces in the path, it errors out.  I checked the source code and line 275 in Parallel.cs is where the problem is.  That guy needs to have quotations around the logging output path to prevent spaces from causing issues.  For now, I'm using a path without any spaces, but I would like to have the full configuration name for my log output location (i.e.  "(somepath)\Mixed Platforms\Release")

Thanks in advance!

**Comment by mikefourie** [comment]
thanks, let me know if the latest code resolves this.

**Comment by CrazeeeCoder** [comment]
Please refer to the comment that I left on your checkin.  I do not believe the provided solution solves the problem.  Now, it may not even run at all when an alternative log file location is provided.

**Comment by mikefourie** [comment]
:-( sorry. let me know if the 2nd attempt fixes it for you
