### ISSUE TITLE
Svn Task caching user details

### ISSUE THREAD

**Issue by crick3t** [mikefourie/MSBuildExtensionPack#38]
Hi All,

I have a small problem with the SVN task. When I try to call any of the actions with a username and password then Tortoise is caching the user details.
I tried to find the solution, but as I can see the extension should use the no-auth-cache, so this should not happen.
What am I doing wrong?

Thanks,
Peter

I am using TortoiseSVN 1.8.11

Task:

``` XML
<UsingTask TaskName="MSBuild.ExtensionPack.Subversion.Svn" AssemblyFile="$(MSBuildProjectDirectory)\packages\MSBuild.Extension.Pack.1.6.0\tools\net40\MSBuild.ExtensionPack.dll " />
  <Target Name="SVNUpdate" AfterTargets="ExcludeFilesFromPackage">
    <MSBuild.ExtensionPack.Subversion.Svn TaskAction="Update" Items="$(SVNROOT)" UserName="BuildUser" UserPassword="SuperSafePassword:)"  />
   </Target>
```

**Comment by mikefourie** [comment]
so you are saying that after running that, the task works but a side effect is that tortoiseSVN uses some cached credential?

**Comment by crick3t** [comment]
The task works, but after running it the user is cached.
Which also means if you have a user already using the SVN then that one is going to be knocked out and replaced by the user defined in the task. When no-auth-cache is used this should not happen.
For example. Lets say one of the devs runs a publish, then his actual user is going to be replaced with the user defined in the task. If they don't log out that user and log in again with their own user then all of their changes are going to be committed with the task's user.
