### ISSUE TITLE
Install - Newbee

### ISSUE THREAD

**Issue by jhallam3** [mikefourie/MSBuildExtensionPack#41]
Hi All, 

Can someone please help me.

Im wanting to develop code on a product called SenseNet and this is a prerequisite, However I cant see how to install or what to do with it to get this product working. 

Any ideas on how to get it installed?

**Comment by RebelFist** [comment]
Find the installer here: https://github.com/mikefourie/MSBuildExtensionPack/releases
Took me a minute as well
