### ISSUE TITLE
Relation between GitHub releases and NuGet packages?

### ISSUE THREAD

**Issue by ArturDorochowicz** [mikefourie/MSBuildExtensionPack#45]
I see release 4.0.12.0 here on GitHub and on NuGet version 1.7.0.0 released around the same time. Are they supposed to be same thing, i.e. same contents?

I'm asking because I was expecting the NuGet version to include 7f7ea8c436c03a1fb224fb6e973fba1c9d4d5275 - change in MSBuild.ExtensionPack.VersionNumber.targets, but it doesn't. What gives?

**Comment by mikefourie** [comment]
I suspect I made a mistake.... will check in a few hours...

**Comment by mikefourie** [comment]
[Fixed](https://www.nuget.org/packages/MSBuild.Extension.Pack/1.8.0)

Thanks for reporting
