### ISSUE TITLE
AssemblyFileRevisionType AutoIncrement

### ISSUE THREAD

**Issue by jeremysimmons** [mikefourie/MSBuildExtensionPack#46]
I just wanted to verify where the AutoIncrement base number is pulled from.
It appears it's reading the base value from the AssemblyInfo.* file.
MSBuildExtensionPack/Solutions/Main/Framework/Framework/AssemblyInfo/AssemblyInfo.cs

If I pull clean sources from my scm on each build, I am assuming (and tests show) that the AutoIncrement schema will not work.

Is there an alternate storage mechanism for the AutoIncrement number I'm missing?

**Comment by mikefourie** [comment]
IIRC that will operate on any files passed into the AssemblyInfoFiles property. If you get a file at the same version each time then the result will be the same each time, unless your are committing that version change.
