### ISSUE TITLE
Documentation doesn't work in Microsoft Edge

### ISSUE THREAD

**Issue by eloekset** [mikefourie/MSBuildExtensionPack#50]
Microsoft Edge fullscreen compared to Google Chrome on top.
![2015-12-17_0847](https://cloud.githubusercontent.com/assets/791721/11864224/0c59a67c-a49b-11e5-998f-b992ffa872fb.png)

**Comment by mikefourie** [comment]
seems to be fine on my edge.
![capture](https://cloud.githubusercontent.com/assets/1269371/11919284/326f82fc-a746-11e5-98fd-aae2f8ef76c2.PNG)
