### ISSUE TITLE
Path to targets file in code comment is incorrect

### ISSUE THREAD

**Issue by eloekset** [mikefourie/MSBuildExtensionPack#51]
For instance the Framework\Signing.cs file has XML comments for the class that contains a code sample. In that sample the file MSBuild.ExtensionsPack.tasks is referred to, but in the NuGet package that file is called MSBuild.Extension.Pack.targets in folder [package-folder]\build\net40\\.
```xml
    /// <code lang="xml"><![CDATA[
    /// <Project ToolsVersion="4.0" DefaultTargets="Default" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
    ///     <PropertyGroup>
    ///         <TPath>$(MSBuildProjectDirectory)\..\MSBuild.ExtensionPack.tasks</TPath>
    ///         <TPath Condition="Exists('$(MSBuildProjectDirectory)\..\..\Common\MSBuild.ExtensionPack.tasks')">$(MSBuildProjectDirectory)\..\..\Common\MSBuild.ExtensionPack.tasks</TPath>
    ///     </PropertyGroup>
```

**Comment by mikefourie** [comment]
I cant remember why that file is named .target in the nuget packages but the msi installs have the .tasks file. I don't think there's a need to change the samples.
