### ISSUE TITLE
AssemblyInfo task DirectSet for AssemblyRevisionType and AssemblyBuildNumberType

### ISSUE THREAD

**Issue by jeremysimmons** [mikefourie/MSBuildExtensionPack#52]
The XML documentation for the AssemblyInfo indicates DirectSet is a valid value for AssemblyRevisionType and AssemblyBuildNumberType. 
https://github.com/mikefourie/MSBuildExtensionPack/search?utf8=%E2%9C%93&q=DirectSet

UpdateVesrionProperty does not contain a path for this enum value.
https://github.com/mikefourie/MSBuildExtensionPack/blob/7f7ea8c436c03a1fb224fb6e973fba1c9d4d5275/Solutions/Main/Framework/Framework/AssemblyInfo/AssemblyInfo.cs#L1276

And it does not exist in the Enum.
https://github.com/mikefourie/MSBuildExtensionPack/blob/7f7ea8c436c03a1fb224fb6e973fba1c9d4d5275/Solutions/Main/Framework/Framework/AssemblyInfo/AssemblyInfo.cs#L18

I'd very much like to have this feature. Would you accept a pull request?

**Comment by jeremysimmons** [comment]
Looks like one workaround is to use the AssemblyInfo.AssemblyFileVersion Property to directly set my value to 1.0.X.Y, since I can't use AssemblyBuildNumber=X AssemblyBuildNumberType=DirectSet and AssemblyRevisionNumber=Y AssemblyRevisonNumberType=DirectSet.

**Comment by mikefourie** [comment]
Hi Jeremy

I'll crack open the code this weekend and work through what you are saying. Of course very happy to take in pull requests.

Mike

**Comment by jeremysimmons** [comment]
Thanks @mikefourie. Based on the XML Comments, I expected the feature to be there. My workaround works, but I'd like the functionality to match the comments. I'm more than happy to send you a pull request. What branch do you want it on?

**Comment by mikefourie** [comment]
on master thanks. This looks like an inherited issue from the original task.
