### ISSUE TITLE
Error Unable to read current AssemblyVersion from file Properties\AssemblyInfo.cs 

### ISSUE THREAD

**Issue by k-samsonov** [mikefourie/MSBuildExtensionPack#57]
if version in AssemblyInfo.cs with full namespace
[assembly: System.Reflection.AssemblyVersion("1.0.0.0")]
[assembly: System.Reflection.AssemblyFileVersion("1.0.0.0")]

**Comment by mikefourie** [comment]
can you provide more info.

**Comment by mikefourie** [comment]
open if more info
