### ISSUE TITLE
Missing instructions on how to use this...

### ISSUE THREAD

**Issue by balmyBanzai** [mikefourie/MSBuildExtensionPack#61]
I don't even know where I'm supposed to start to use any of this. Please add that info or a link to that info in your README

**Comment by mikefourie** [comment]
the home page links to http://www.msbuildextensionpack.com/ which has the help files. Is that not enough?

**Comment by jbaehr** [comment]
@mikefourie would you mind adding the link http://www.msbuildextensionpack.com/ to the github project description? My entry point was the "ProjectUrl" from the nuget, which points to this github project. That's fine. However, from here I could not find any reference to the above mentioned website.  
 * The github project descriptions states "_No description, website, or topics provided._"
 * The readme has a badge that links to a readthedocs page with no content
 * The readme has a paragraph that says "Each task is documented ..." but gives no hint on where to find this documentation
 * The repo contains a `.chm` file of 1.8 MB which displays on my Win10 machine only the index but no content

Eventually I found this very issue which points be to the homepage. There I finally found a working documentation and the useful link to your [MSBuild Explorer](http://www.msbuildexplorer.com/) (nice tool, btw! together with [MSBuild Log Viewer](http://www.msbuildlog.com/) a must-have for any msbuild related work).

My wish: Please make it easier to find the homepage, when comming from github. Just mention http://www.msbuildextensionpack.com/ in the project description and the readme. Done.
