### ISSUE TITLE
Unable to build solution due to Enterprise requirements

### ISSUE THREAD

**Issue by cori** [mikefourie/MSBuildExtensionPack#65]
I'm attempting to build the solution with an eye towards potentially contributing some additional tasks that I've had the need for, but I can't build the solution as configured due to a reliance on VS Enterprise-only features - specifically Microsoft.QualityTools.Testing.Fakes.

This is as much a comment as anything else - I'm aware I can just not build the FrameworkUnitTests project and go on with my life, which is what I did for my own purposes, but it's disappointing to have the desire and wherewithal to contribute but not to be able to engage fully due some libraries relied on by the project  being unavailable. Feel free to close the ticket as "Won't Fix"; just wanted to voice my concerns.

**Comment by mikefourie** [comment]
Thanks for the feedback,
