### ISSUE TITLE
Licensing is unclear

### ISSUE THREAD

**Issue by cori** [mikefourie/MSBuildExtensionPack#66]
There is no licensing declared in the README.md file. On the distribution site (http://www.msbuildextensionpack.com/) the code is noted, vaguely, as being "open source". On the documentation site (http://www.msbuildextensionpack.com/help/4.0.12.0/index.html) an all-rights copyright is asserted, and in the source files (at least the ones that I've interacted with) there's a reference to the Microsoft Permissive License with all *other* rights reserved.

I can't find any current reference to the Microsoft Permissive License aside from an rtf download from the XBox site.  However the license abbreviation (Ms-Pl) and actual content seem to be identical to the Microsoft Public License (https://msdn.microsoft.com/en-us/library/ff649456.aspx). The link in the source files to http://www.microsoft.com/resources/sharedsource/licensingbasics/sharedsourcelicenses.mspx now redirects to https://www.microsoft.com/resources/sharedsource/default.mspx which in turn redirects to https://www.microsoft.com/en-us/sharedsource/default.aspx which seems to be focused on the Shared Source initiative for partners to be granted access to the source code to things like the .Net Framework, not to "open source" efforts from within Microsoft.

All of this makes it extremely difficult for a developer to know what rights are granted for creating or distributing derivative works or using this work in commercial applications and whether attribution is required. For instance if I use an extension to an existing MSBuildExtension in a continuous integration implementation that generates a publicly available web site that I charge for access to do I need to note that in the site's 3rd party licenses list? I don't *think* so, nor do I think I need to pay a fee for such usage. But it's a little unclear.

Not to mention that, but even if I felt completely certain about my interpretation of the situation, I'm pretty sure that the cadre of lawyers looking out for my employers' or clients' best interests would be unwillling to accept my word for it.

**Really** not trying to be a pain in the neck here, but this does pose a real-world problem that I am unsure how to address.

**Comment by mikefourie** [comment]
Thanks for the feedback. I'm working on a 4.x update release to clarify the licensing.

**Comment by mikefourie** [comment]
Release https://github.com/mikefourie/MSBuildExtensionPack/releases/tag/4.0.15.0 contains MIT clarity. Let me know if you have any other concerns. Thanks for the feedback.
