### ISSUE TITLE
Unable to make HttpWebRequest call using TLS 1.2

### ISSUE THREAD

**Issue by imiTester** [mikefourie/MSBuildExtensionPack#70]
The httpWebRequest currently can't use the TLS 1.2 security protocol because of .NET 4.0. Any plans to upgrade to .NET 4.5 and to support TLS 1.2?

**Comment by mikefourie** [comment]
Hi, yes will take a look

**Comment by mikefourie** [comment]
https://github.com/mikefourie/MSBuildExtensionPack/releases/tag/4.0.15.0 targets 4.7.

**Comment by mikefourie** [comment]
will push this out with the next release. if you need it now simply rebuild the code.
