### ISSUE TITLE
Nunit3 OutputXMLFile path is escaped

### ISSUE THREAD

**Issue by pbronneberg** [mikefourie/MSBuildExtensionPack#71]
The Nunit3 task uses an `TaskItem` for the `OutputXMLFile` property. `TaskItem.ItemSpec` returns an escaped string. Because of this, the NUNit3 task will break in case special characters are used in a pathname (e.g. in case the path is `workspace@2\temp`, this results in ``workspace%402\temp`)

Is there a reason why TaskItem is used for the properties containing paths instead of a standard string? If not I'll happily create a PR to fix this!

**Comment by mikefourie** [comment]
If I remember correctly, any path property uses an ITaskItem. This is so metadata can be queried and relative properties can be assigned. Will be better off handling the special characters.
