### ISSUE TITLE
Nuget Gallery is out of date

### ISSUE THREAD

**Issue by stffabi** [mikefourie/MSBuildExtensionPack#72]
The nuget gallery seems to be quite out of date. Could it be udpated to the latest version?

**Comment by mikefourie** [comment]
Done - https://www.nuget.org/packages/MSBuild.Extension.Pack/1.9.1 has the 4.0.15.0 bits

**Comment by stffabi** [comment]
Thanks

**Comment by abbeycode** [comment]
Why not have the version numbers in the NuGet feed line up with the ones on GitHub? It's confusing - I had to find this issue to know that 1.9.1 is actually up to date.
