### ISSUE TITLE
MSBuild.ExtensionPack.FileSystem.RoboCopy fails with Code 16 if source path has spaces in name

### ISSUE THREAD

**Issue by MagicAndre1981** [mikefourie/MSBuildExtensionPack#73]
I've added a [MSBuild.ExtensionPack.FileSystem.RoboCopy](https://github.com/mikefourie/MSBuildExtensionPack/blob/master/Solutions/Main/Framework/FileSystem/RoboCopy.cs) task to copy the output to a remote device to do remote debugging:

```
<Target Name="AfterBuild">
    <MSBuild.ExtensionPack.FileSystem.RoboCopy Source="$(TargetDir)\" Destination="\\Foo\Bar" Files="@(OutputFiles)">
      <Output TaskParameter="ExitCode" PropertyName="Exit" />
      <Output TaskParameter="ReturnCode" PropertyName="Return" />
    </MSBuild.ExtensionPack.FileSystem.RoboCopy>
    <Message Text="ExitCode = $(Exit)" />
    <Message Text="ReturnCode = $(Return)" />
  </Target>
```

This works fine until the source path has spaces, here the task fails with robocopy return code 16.

I use VS2017-15.4, Win10 v1709 with a WinForms 4.7.1 project.

**Comment by mikefourie** [comment]
Spaces should be handled fine. I can't repro this. Can you send log output?

working sample

     <MSBuild.ExtensionPack.FileSystem.RoboCopy **Source="c:\aa - Copy\"** Destination="\\foo\bar" Files="@(OutputFiles)">
        <Output TaskParameter="ExitCode" PropertyName="Exit" />
        <Output TaskParameter="ReturnCode" PropertyName="Return" />
      </MSBuild.ExtensionPack.FileSystem.RoboCopy>
      <Message Text="ExitCode = $(Exit)" />
      <Message Text="ReturnCode = $(Return)" />
