### ISSUE TITLE
After upgrading to VS 2017, $MSbuildExtensionPath cannot resolve  iLmerge.Csharp.Targets

### ISSUE THREAD

**Issue by weedkiller** [mikefourie/MSBuildExtensionPack#74]
After updating/upgrading the solution to VS 2017, MSbuildExtension path cannot resolve to ILmerge

Can you please tell me how to resolve this error... I have attached the error

![image](https://user-images.githubusercontent.com/21086190/32031372-d5c55b2e-b9ce-11e7-9d9f-c3196552818f.png)

The CS proj file with the non resolving build targets

![image](https://user-images.githubusercontent.com/21086190/32031420-1c5fd488-b9cf-11e7-9a5a-0270d2c6ffe2.png)

thanks

**Comment by mikefourie** [comment]
this is unrelated to the MSBuild Extension Pack. you should touch base with https://www.nuget.org/packages/MSBuild.ILMerge.Task/ and also note that MSbuildExtensionPath behaves slightly differently from vs 2017
