### ISSUE TITLE
Hard-coded install path in MSBuild.ExtensionPack.tasks broken by different install path

### ISSUE THREAD

**Issue by RobCoder** [mikefourie/MSBuildExtensionPack#82]
Seems like the install path got changed recently, which breaks existing import statements. This would not be a big deal, since the installer allows the user to specify a different install path, but unfortunately the default install path is also hard-coded into MSBuild.ExtensionPack.tasks. If a different install path is selected in the installer (such as the previous MSBuild/ExtensionPack), it results in MSBuild being unable to find the assemblies that implement the tasks, because the paths in MSBuild.ExtensionPack.tasks are wrong.

Not sure the best way to fix it. An env var added by the installer to indicate the install path would work.

**Comment by mikefourie-zz** [comment]
you could specify an environment variable called ExtensionTasksPath and that will override anything in the provided .tasks file if you install to a different location.
