### ISSUE TITLE
Cannot find NUnit3 on 32-bit operating system

### ISSUE THREAD

**Issue by EbenZhang** [mikefourie/MSBuildExtensionPack#83]
in the code it seems the toolpath is hard coded to %programfiles(x86)% thus the error
```
The specified task executable location "%programfiles(x86)%\NUnit.org\nunit-console\nunit3-console.exe" is invalid.
```

**Comment by mikefourie-zz** [comment]
you can specify ToolPath if the default fallback doesn't work for you

`if (string.IsNullOrEmpty(this.ToolPath))
            {
                this.ToolPath = Environment.ExpandEnvironmentVariables(@"%programfiles(x86)%\NUnit.org\nunit-console");
            }`

**Comment by EbenZhang** [comment]
will be better if the extension can handle it automatically since people may have 32 bits as well as 64 bits build agents
