### ISSUE TITLE
StyleCop 4.7.55 does not work with March 2015 release

### ISSUE THREAD

**Issue by MonkeyTennis** [mikefourie/MSBuildExtensionPack#86]
Hi

We've recently upgraded to StyleCop v4.7.55 and are attempting to run it against the March 2015 release. However, this fails with the following exception:

MissingMethodException: Method not found: 'Void StyleCop.CodeProject..ctor(Int32, System.String, StyleCop.Configuration)'.\r

This is occurring because the constructor signature has changed between versions 4.7.49 and 4.7.55 to include a new optional parameter.

Have you had this same issue and is there a plan to release a version of the extensions that work with the latest versions of StyleCop?

Thanks

Brad

**Comment by mikefourie-zz** [comment]
Hi Brad, I tried compiling against the 4.7.55 release and got parsing working, however violations are not detected. I've got no plans to spend any more time on StyleCop. I suggest looking at editorconfig https://docs.microsoft.com/en-us/visualstudio/ide/create-portable-custom-editor-options which IIRC will soon support build time validation too.
