### ISSUE TITLE
Version format artificially constraining - e.g. SemVer support

### ISSUE THREAD

**Issue by jtu100** [mikefourie/MSBuildExtensionPack#9]
The AssemblyInfo.cs class uses the Version class to parse provided version strings. That severely limits valid inputs, and stops it being compatible with SemVer.

Version class ctor being used forces you to use a 4 component version string for BOTH the AssemblyVersion AND AssemblyFileVersion when in fact neither require this limitation.

The AssemblyVersion should accept anything between 1 and 4 component version.
The AssemblyFileVersion is actually free text and you can put anything you want in there.

A way to disable this over specificity would be useful.

**Comment by haakoo** [comment]
Just ran into this problem myself now. We'd like to only use a three-part version string for AssemblyVersion. I might have a look at the code and see if I can make a fix.
